# Generated by Django 5.2.5 on 2025-08-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtextile', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
