# Generated by Django 5.2.5 on 2025-08-30 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtextile', '0003_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
